apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: <place-name-here>
spec:
  params:
  # Add parameters here
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: cd-pipeline-run-
      spec:
      # Add pipeline definition here
